# Generated by Django 4.2.5 on 2023-10-02 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0002_place_district_alter_district_name_alter_place_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='district',
        ),
        migrations.DeleteModel(
            name='District',
        ),
        migrations.DeleteModel(
            name='Place',
        ),
    ]
