# Generated by Django 4.2.5 on 2023-09-30 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0002_alter_details_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='account_type',
            field=models.CharField(choices=[('saving account', 'Saving Account'), ('current account', 'Current Account')], max_length=20),
        ),
        migrations.AlterField(
            model_name='details',
            name='materials_provide',
            field=models.CharField(max_length=200),
        ),
    ]
