# Generated by Django 4.2.5 on 2023-10-01 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0003_alter_details_account_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='details',
            name='materials_provide',
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credentials.district')),
            ],
        ),
        migrations.AlterField(
            model_name='details',
            name='account_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credentials.accounttype'),
        ),
        migrations.AlterField(
            model_name='details',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credentials.branch'),
        ),
        migrations.AlterField(
            model_name='details',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credentials.district'),
        ),
        migrations.AddField(
            model_name='details',
            name='materials_provide',
            field=models.ManyToManyField(to='credentials.material'),
        ),
    ]
