# Generated by Django 4.2.5 on 2023-10-02 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0004_accounttype_district_material_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='district',
        ),
        migrations.RemoveField(
            model_name='details',
            name='account_type',
        ),
        migrations.RemoveField(
            model_name='details',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='details',
            name='district',
        ),
        migrations.RemoveField(
            model_name='details',
            name='materials_provide',
        ),
        migrations.DeleteModel(
            name='AccountType',
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
        migrations.DeleteModel(
            name='Details',
        ),
        migrations.DeleteModel(
            name='District',
        ),
        migrations.DeleteModel(
            name='Material',
        ),
    ]
